sudo: required
services:
  - docker
before_install:
  - docker build -t greshmashaji123/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true greshmashaji123/react-test npm test

after_success:
  - docker build -t greshmashaji123/multi-client ./client
  - docker build -t greshmashaji123/multi-nginx ./nginx
  - docker build -t greshmashaji123/multi-server ./server
  - docker build -t greshmashaji123/multi-worker ./worker 

  - echo '$DOCKER_PASSWORD' | docker login -u "$DOCKER_ID" --password-stdin

  - docker push greshmashaji123/multi-client
  - docker push greshmashaji123/multi-server
  - docker push greshmashaji123/multi-nginx
  - docker push greshmashaji123/multi-worker


